name: CI Pipeline for React Todo App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  frontend-build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    strategy: # define matrix for multiple Node.js versions and it run job in parallel for each version
      matrix:
        node-version: [18.x, 20.x, 21.x]
    
    steps:
      - name: Checkout code # clone the repo if not already present
        uses: actions/checkout@v4 # using action tool to checkout code using keyword 'uses'
      
      - name: Setup Node.js ${{ matrix.node-version }} # setup Node.js environment for each version in matrix
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # enable caching for npm dependencies
          cache-dependency-path: '**/package-lock.json' # spe
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
        continue-on-error: false
      
      #- name: Run tests
        #run: npm test -- --coverage --watchAll=false
       # env:
        #  CI: true
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build-${{ matrix.node-version }}
          path: build/
          retention-days: 7
      
      